filebeat.inputs:
# Monitor Pino JSON log files (including rotated files)
- type: log
  paths:
    - /app/logs/*.log
    - /app/logs/*.*.log  # Include rotated files with date extensions
  json.keys_under_root: true
  json.add_error_key: true
  close_inactive: 1h  # Close file handles after 1 hour of inactivity
  scan_frequency: 10s  # Scan for new files every 10 seconds
  processors:
    - timestamp:
        field: "@timestamp"
        layouts:
          - '2006-01-02T15:04:05.000Z'

# Output to Elasticsearch Cloud
output.elasticsearch:
  hosts: 
    - "ELASTICSEARCH_CLOUD_URL_PLACEHOLDER"
  api_key: "ELASTICSEARCH_API_KEY_PLACEHOLDER"
  
  # Use default Filebeat index pattern (filebeat-*)
  # This automatically gets proper templates and pipeline processing
  
# Disable template setup to avoid conflicts with existing templates
setup.template.enabled: false
setup.ilm.enabled: false

# Logging configuration
logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

# Monitoring disabled for simplicity
monitoring.enabled: false